### ISSUE TITLE
[Bug]: Flag typo in xs_sdk_sim

### ISSUE THREAD

**Issue by WenkaiQin** [Interbotix/interbotix_ros_core#30]
### What happened?

On lines 273, 296 of xs_sdk_sim, execute is typo'd.

https://github.com/Interbotix/interbotix_ros_core/blob/main/interbotix_ros_xseries/interbotix_xs_sdk/scripts/xs_sdk_sim#L273

### Robot Model

wxxmd

### Operating System

Ubuntu 20.04

### ROS Distro

ROS 1 Noetic

**Comment by LSinterbotix** [comment]
Fixed in https://github.com/Interbotix/interbotix_ros_core/commit/c1bbd9c1fc87a5494cda0e766f0f392681abda37.
