### ISSUE TITLE
 Locobot wx250 6dof, cant find Dynamixel ids 11,2,10,1

### ISSUE THREAD

**Issue by dazednconfusing** [Interbotix/interbotix_ros_core#5]
Hi,

Can I please get a list of the dynamixel Locobot wx250 6dof motor model numbers and what their default values should be in the dynamixel2 wizard, **especially the id**? I believe I need to factory reset to fix the following issue and then manually reset the default values in the wizard as the wizard cannot even find the motors.

**Running:**
`
roslaunch interbotix_xslocobot_control xslocobot_control.launch robot_model:=locobot_wx250s use_base:=true use_camera
`

**Results in:**
- `[ERROR] [1636917225.053295919]: [xs_sdk] Can't find Dynamixel ID '11', Joint Name : 'tilt'`
- ` [ERROR] [1636917225.329180603]: [xs_sdk] Can't find Dynamixel ID '2', Joint Name : 'shoulder'`
- ` [ERROR] [1636917225.365294906]: [xs_sdk] Can't find Dynamixel ID '10', Joint Name : 'pan'`
- ` [ WARN] [1636917225.371856929]: Kobuki : no data stream, is kobuki turned on?`
- ` [ERROR] [1636917225.497168871]: [xs_sdk] Can't find Dynamixel ID '1', Joint Name : 'waist'`
- ` [ERROR] [1636917225.497222294]: [xs_sdk] Could not find all motors. Shutting down...`

**And further:**
- The dynamixel wizard cannot find them searching over all ids, protocols, and baud rates: 

**Note**: There used to be an issue where there were two devices with IDs 1 and 2 found but one pair had baud rate 1mbps and the other with 57600. However, after changing the baud rates of the latter to 1mbps  only IDs 3-9 are being found (with the most exhuastive scan).

**The entire roslaunch output is:**
`
... logging to /home/locobot/.ros/log/fbc5682e-457e-11ec-8399-131618a9447b/roslaunch-locobot-3178.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://10.0.0.25:37907/

SUMMARY
========

PARAMETERS
 * /locobot/camera/realsense2_camera/accel_fps: 250
 * /locobot/camera/realsense2_camera/accel_frame_id: locobot/camera_ac...
 * /locobot/camera/realsense2_camera/accel_optical_frame_id: locobot/camera_ac...
 * /locobot/camera/realsense2_camera/align_depth: False
 * /locobot/camera/realsense2_camera/aligned_depth_to_color_frame_id: locobot/camera_al...
 * /locobot/camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: locobot/camera_al...
 * /locobot/camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: locobot/camera_al...
 * /locobot/camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: locobot/camera_al...
 * /locobot/camera/realsense2_camera/aligned_depth_to_infra1_frame_id: locobot/camera_al...
 * /locobot/camera/realsense2_camera/aligned_depth_to_infra2_frame_id: locobot/camera_al...
 * /locobot/camera/realsense2_camera/allow_no_texture_points: False
 * /locobot/camera/realsense2_camera/base_frame_id: locobot/camera_link
 * /locobot/camera/realsense2_camera/calib_odom_file: 
 * /locobot/camera/realsense2_camera/clip_distance: -2.0
 * /locobot/camera/realsense2_camera/color_fps: 30
 * /locobot/camera/realsense2_camera/color_frame_id: locobot/camera_co...
 * /locobot/camera/realsense2_camera/color_height: 480
 * /locobot/camera/realsense2_camera/color_optical_frame_id: locobot/camera_co...
 * /locobot/camera/realsense2_camera/color_width: 640
 * /locobot/camera/realsense2_camera/depth_fps: 30
 * /locobot/camera/realsense2_camera/depth_frame_id: locobot/camera_de...
 * /locobot/camera/realsense2_camera/depth_height: 480
 * /locobot/camera/realsense2_camera/depth_optical_frame_id: locobot/camera_de...
 * /locobot/camera/realsense2_camera/depth_width: 640
 * /locobot/camera/realsense2_camera/device_type: 
 * /locobot/camera/realsense2_camera/enable_accel: False
 * /locobot/camera/realsense2_camera/enable_color: True
 * /locobot/camera/realsense2_camera/enable_depth: True
 * /locobot/camera/realsense2_camera/enable_fisheye1: False
 * /locobot/camera/realsense2_camera/enable_fisheye2: False
 * /locobot/camera/realsense2_camera/enable_fisheye: False
 * /locobot/camera/realsense2_camera/enable_gyro: False
 * /locobot/camera/realsense2_camera/enable_infra1: False
 * /locobot/camera/realsense2_camera/enable_infra2: False
 * /locobot/camera/realsense2_camera/enable_infra: False
 * /locobot/camera/realsense2_camera/enable_pointcloud: False
 * /locobot/camera/realsense2_camera/enable_pose: False
 * /locobot/camera/realsense2_camera/enable_sync: False
 * /locobot/camera/realsense2_camera/filters: 
 * /locobot/camera/realsense2_camera/fisheye1_frame_id: locobot/camera_fi...
 * /locobot/camera/realsense2_camera/fisheye1_optical_frame_id: locobot/camera_fi...
 * /locobot/camera/realsense2_camera/fisheye2_frame_id: locobot/camera_fi...
 * /locobot/camera/realsense2_camera/fisheye2_optical_frame_id: locobot/camera_fi...
 * /locobot/camera/realsense2_camera/fisheye_fps: 30
 * /locobot/camera/realsense2_camera/fisheye_frame_id: locobot/camera_fi...
 * /locobot/camera/realsense2_camera/fisheye_height: 480
 * /locobot/camera/realsense2_camera/fisheye_optical_frame_id: locobot/camera_fi...
 * /locobot/camera/realsense2_camera/fisheye_width: 640
 * /locobot/camera/realsense2_camera/gyro_fps: 400
 * /locobot/camera/realsense2_camera/gyro_frame_id: locobot/camera_gy...
 * /locobot/camera/realsense2_camera/gyro_optical_frame_id: locobot/camera_gy...
 * /locobot/camera/realsense2_camera/imu_optical_frame_id: locobot/camera_im...
 * /locobot/camera/realsense2_camera/infra1_frame_id: locobot/camera_in...
 * /locobot/camera/realsense2_camera/infra1_optical_frame_id: locobot/camera_in...
 * /locobot/camera/realsense2_camera/infra2_frame_id: locobot/camera_in...
 * /locobot/camera/realsense2_camera/infra2_optical_frame_id: locobot/camera_in...
 * /locobot/camera/realsense2_camera/infra_fps: 30
 * /locobot/camera/realsense2_camera/infra_height: 480
 * /locobot/camera/realsense2_camera/infra_rgb: False
 * /locobot/camera/realsense2_camera/infra_width: 640
 * /locobot/camera/realsense2_camera/initial_reset: False
 * /locobot/camera/realsense2_camera/json_file_path: 
 * /locobot/camera/realsense2_camera/linear_accel_cov: 0.01
 * /locobot/camera/realsense2_camera/odom_frame_id: locobot/camera_od...
 * /locobot/camera/realsense2_camera/pointcloud_texture_index: 0
 * /locobot/camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /locobot/camera/realsense2_camera/pose_frame_id: locobot/camera_po...
 * /locobot/camera/realsense2_camera/pose_optical_frame_id: locobot/camera_po...
 * /locobot/camera/realsense2_camera/publish_odom_tf: True
 * /locobot/camera/realsense2_camera/publish_tf: True
 * /locobot/camera/realsense2_camera/rosbag_filename: 
 * /locobot/camera/realsense2_camera/serial_no: 
 * /locobot/camera/realsense2_camera/tf_publish_rate: 0.0
 * /locobot/camera/realsense2_camera/topic_odom_in: odom_in
 * /locobot/camera/realsense2_camera/unite_imu_method: 
 * /locobot/camera/realsense2_camera/usb_port_id: 
 * /locobot/diagnostic_aggregator/analyzers/input_ports/contains: ['Digital Input',...
 * /locobot/diagnostic_aggregator/analyzers/input_ports/path: Input Ports
 * /locobot/diagnostic_aggregator/analyzers/input_ports/remove_prefix: mobile_base_nodel...
 * /locobot/diagnostic_aggregator/analyzers/input_ports/timeout: 5.0
 * /locobot/diagnostic_aggregator/analyzers/input_ports/type: diagnostic_aggreg...
 * /locobot/diagnostic_aggregator/analyzers/kobuki/contains: ['Watchdog', 'Mot...
 * /locobot/diagnostic_aggregator/analyzers/kobuki/path: Kobuki
 * /locobot/diagnostic_aggregator/analyzers/kobuki/remove_prefix: mobile_base_nodel...
 * /locobot/diagnostic_aggregator/analyzers/kobuki/timeout: 5.0
 * /locobot/diagnostic_aggregator/analyzers/kobuki/type: diagnostic_aggreg...
 * /locobot/diagnostic_aggregator/analyzers/power/contains: ['Battery']
 * /locobot/diagnostic_aggregator/analyzers/power/path: Power System
 * /locobot/diagnostic_aggregator/analyzers/power/remove_prefix: mobile_base_nodel...
 * /locobot/diagnostic_aggregator/analyzers/power/timeout: 5.0
 * /locobot/diagnostic_aggregator/analyzers/power/type: diagnostic_aggreg...
 * /locobot/diagnostic_aggregator/analyzers/sensors/contains: ['Cliff Sensor', ...
 * /locobot/diagnostic_aggregator/analyzers/sensors/path: Sensors
 * /locobot/diagnostic_aggregator/analyzers/sensors/remove_prefix: mobile_base_nodel...
 * /locobot/diagnostic_aggregator/analyzers/sensors/timeout: 5.0
 * /locobot/diagnostic_aggregator/analyzers/sensors/type: diagnostic_aggreg...
 * /locobot/diagnostic_aggregator/base_path: 
 * /locobot/diagnostic_aggregator/pub_rate: 1.0
 * /locobot/joint_state_publisher/rate: 100
 * /locobot/joint_state_publisher/source_list: ['dynamixel/joint...
 * /locobot/mobile_base/acceleration_limiter: True
 * /locobot/mobile_base/base_frame: locobot/base_foot...
 * /locobot/mobile_base/battery_capacity: 16.5
 * /locobot/mobile_base/battery_dangerous: 13.2
 * /locobot/mobile_base/battery_low: 14.0
 * /locobot/mobile_base/cmd_vel_timeout: 2.0
 * /locobot/mobile_base/device_port: /dev/kobuki
 * /locobot/mobile_base/odom_frame: locobot/odom
 * /locobot/mobile_base/publish_tf: True
 * /locobot/mobile_base/use_imu_heading: True
 * /locobot/mobile_base/wheel_left_joint_name: wheel_left_joint
 * /locobot/mobile_base/wheel_right_joint_name: wheel_right_joint
 * /locobot/robot_description: <?xml version="1....
 * /locobot/use_base: True
 * /locobot/xs_sdk/load_configs: True
 * /locobot/xs_sdk/mode_configs: /home/locobot/int...
 * /locobot/xs_sdk/motor_configs: /home/locobot/int...
 * /rosdistro: noetic
 * /rosversion: 1.15.13

NODES
  /locobot/
    diagnostic_aggregator (diagnostic_aggregator/aggregator_node)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    mobile_base (nodelet/nodelet)
    mobile_base_nodelet_manager (nodelet/nodelet)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    xs_sdk (interbotix_xs_sdk/xs_sdk)
  /locobot/camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [3196]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to fbc5682e-457e-11ec-8399-131618a9447b
process[rosout-1]: started with pid [3209]
started core service [/rosout]
process[locobot/joint_state_publisher-2]: started with pid [3212]
process[locobot/robot_state_publisher-3]: started with pid [3213]
process[locobot/xs_sdk-4]: started with pid [3218]
process[locobot/mobile_base_nodelet_manager-5]: started with pid [3219]
process[locobot/mobile_base-6]: started with pid [3220]
process[locobot/diagnostic_aggregator-7]: started with pid [3221]
process[locobot/camera/realsense2_camera_manager-8]: started with pid [3226]
[ INFO] [1636917224.980629005]: [xs_sdk] Successfully retrieved motor configs from /home/locobot/interbotix_ws/src/interbotix_ros_rovers/interbotix_ros_xslocobots/interbotix_xslocobot_control/config/locobot_wx250s.yaml.
process[locobot/camera/realsense2_camera-9]: started with pid [3244]
[ INFO] [1636917225.022630950]: Initializing nodelet with 4 worker threads.
[ERROR] [1636917225.053295919]: [xs_sdk] Can't find Dynamixel ID '11', Joint Name : 'tilt'
[ INFO] [1636917225.089224718]: [xs_sdk] Found Dynamixel ID : 8, Joint Name : wrist_rotate, Model Number : 1060
[ INFO] [1636917225.137209463]: [xs_sdk] Found Dynamixel ID : 7, Joint Name : wrist_angle, Model Number : 1020
[ INFO] [1636917225.185173896]: [xs_sdk] Found Dynamixel ID : 5, Joint Name : elbow_shadow, Model Number : 1020
[ INFO] [1636917225.233157738]: [xs_sdk] Found Dynamixel ID : 4, Joint Name : elbow, Model Number : 1020
[ INFO] [1636917225.281192387]: [xs_sdk] Found Dynamixel ID : 6, Joint Name : forearm_roll, Model Number : 1020
[ERROR] [1636917225.329180603]: [xs_sdk] Can't find Dynamixel ID '2', Joint Name : 'shoulder'
[ERROR] [1636917225.365294906]: [xs_sdk] Can't find Dynamixel ID '10', Joint Name : 'pan'
[ WARN] [1636917225.371856929]: Kobuki : no data stream, is kobuki turned on?
[ INFO] [1636917225.401162692]: [xs_sdk] Found Dynamixel ID : 9, Joint Name : gripper, Model Number : 1060
[ INFO] [1636917225.443665894]: RealSense ROS v2.2.20
[ INFO] [1636917225.443699903]: Built with LibRealSense v2.40.0
[ INFO] [1636917225.443720787]: Running with LibRealSense v2.40.0
[ INFO] [1636917225.449267184]: [xs_sdk] Found Dynamixel ID : 3, Joint Name : shoulder_shadow, Model Number : 1020
[ INFO] [1636917225.451807681]:  
[ERROR] [1636917225.497168871]: [xs_sdk] Can't find Dynamixel ID '1', Joint Name : 'waist'
[ERROR] [1636917225.497222294]: [xs_sdk] Could not find all motors. Shutting down...
[ERROR] [1636917225.497245827]: [xs_sdk] For troubleshooting, please see https://github.com/Interbotix/interbotix_ros_core/blob/main/interbotix_ros_xseries/interbotix_xs_sdk/TROUBLESHOOTING.md
[ INFO] [1636917225.558658309]: Device with serial number 050522071880 was found.

[ INFO] [1636917225.558719476]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/video4linux/video0 was found.
[ INFO] [1636917225.558754841]: Device with name Intel RealSense D435 was found.
[ INFO] [1636917225.559354479]: Device with port number 2-3 was found.
[ INFO] [1636917225.559404888]: Device USB type: 3.2
[ INFO] [1636917225.561998886]: getParameters...
[ INFO] [1636917225.633332159]: setupDevice...
[ INFO] [1636917225.633359915]: JSON file is not provided
[ INFO] [1636917225.633375445]: ROS Node Namespace: locobotcamera
[ INFO] [1636917225.633398305]: Device Name: Intel RealSense D435
[ INFO] [1636917225.633415705]: Device Serial No: 050522071880
[ INFO] [1636917225.633433365]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/video4linux/video0
[ INFO] [1636917225.633449703]: Device FW version: 05.11.01.100
[ INFO] [1636917225.633464936]: Device Product ID: 0x0B07
[ INFO] [1636917225.633481768]: Enable PointCloud: Off
[ INFO] [1636917225.633503377]: Align Depth: Off
[ INFO] [1636917225.633521341]: Sync Mode: Off
[ INFO] [1636917225.633559449]: Device Sensors: 
[ INFO] [1636917225.635549137]: Stereo Module was found.
 14/11 13:13:45,636 WARNING [140185696069376] (backend-v4l2.cpp:1271) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!
[ INFO] [1636917225.641619226]: RGB Camera was found.
[ INFO] [1636917225.641650035]: num_filters: 0
[ INFO] [1636917225.641670355]: Setting Dynamic reconfig parameters.
[locobot/xs_sdk-4] process has finished cleanly
log file: /home/locobot/.ros/log/fbc5682e-457e-11ec-8399-131618a9447b/locobot-xs_sdk-4*.log
[ WARN] [1636917225.752122952]: Param '/locobot/camera/rgb_camera/power_line_frequency' has value 3 that is not in the enum { {50Hz: 1} {60Hz: 2} {Disabled: 0} }. Removing this parameter from dynamic reconfigure options.
[ INFO] [1636917225.760708153]: Done Setting Dynamic reconfig parameters.
[ INFO] [1636917225.763874968]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1636917225.765353227]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1636917225.765430664]: setupPublishers...
[ INFO] [1636917225.774201334]: Expected frequency for depth = 30.00000
[ INFO] [1636917225.829489023]: Expected frequency for color = 30.00000
[ INFO] [1636917225.847567868]: setupStreams...
[ INFO] [1636917225.848312045]: insert Depth to Stereo Module
[ INFO] [1636917225.848350627]: insert Color to RGB Camera
[ INFO] [1636917225.958405865]: SELECTED BASE:Depth, 0
[ INFO] [1636917225.985210663]: RealSense Node Is Up!
^C[locobot/camera/realsense2_camera-9] killing on exit
[locobot/camera/realsense2_camera_manager-8] killing on exit
[locobot/diagnostic_aggregator-7] killing on exit
[locobot/mobile_base_nodelet_manager-5] killing on exit
[locobot/robot_state_publisher-3] killing on exit
[locobot/joint_state_publisher-2] killing on exit
[locobot/mobile_base-6] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
`

**Comment by LSinterbotix** [comment]
Answered in https://github.com/Interbotix/interbotix_ros_rovers/issues/5#issuecomment-969107478. Please continue the conversation there. Closing.
